### PR TITLE
Get exception from before hook

### PR DESCRIPTION
**Pull request by KorranForce**
Doing pull request first time. If there are any problems - point me.

### CODE REVIEW

**Comment by tk8817** [comment]
Hey @9ikhan have a look at this, I think we should make this a PR directly on allure-cucumber once you have my PRs merged in. 

@KorranForce sorry for the delay, I am waiting for the allure-cucumber team to merge the existing PR's before getting this handled. Its good work.

**Comment by KorranForce** [comment]
@tk8817, well, actually it's me who delayed PR. Sorry for that. Next time I won't be so slow.

**Comment by tk8817** [comment]
@KorranForce sorry for deleting my comments. I decided to merge this, as it works out perfectly. I have an open PR in the allure-cucumber repo right now which relates to this issue.

https://github.com/allure-framework/allure-cucumber/pull/38

together our code makes the full solution to the problem.

**Comment by KorranForce** [comment]
@tk8817, it's fine. Glad if I can help.

**Pull request merged**
